### ISSUE TITLE
OpenHAB - Ce réglage n'est disponible qu'en mode routeur

### ISSUE THREAD

**Issue by Mickaelh51** [MatMaul/freeboxos-java#2]
Hi all,
I have an issue with new Freebox binding (v1.8).
I can see in log:
"2015-06-07 19:45:08.347 [INFO ] [.o.b.f.internal.FreeboxBinding] - Ce réglage n'est disponible qu'en mode routeur"

Ok it's clear, my freebox is a bridge mode. But before with version 1.6, this binding worked.

With this two versions I have two commands in Items conf:
1.6: OK / 1.8: NOK

String Freebox_Xdsl_Status "Status XDSL [%s]" (G_All_House) {freebox="xdsl_status"}
String Freebox_Cs_State "Line State [%s]" (G_All_House) {freebox="line_status"}

Have you an idea for me ?

ref: https://github.com/openhab/openhab/pull/2469#issuecomment-110130055

thanks in advance

**Comment by lolodomo** [comment]
This issue can be closed. It is in fact an issue in the openHAB binding (exception not well handled), not an issue in the library.
I have already fixed the issue in openHAB without the need to touch the code of the library.

Note that one thing could be improved in the library, that is including in the error message (when an exception is triggered) the identification of the called Freebox API.
